CI: support builds on forks
Update ci.yaml

Update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -5,86 +5,107 @@ jobs:
     name: Run Tests
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v2
-    - uses: actions/setup-go@v2
-      with:
-        go-version: '1.18.7'
-    - shell: bash
-      run: |
-        make manifests
-        if [[ -n $(git status -s) ]] ; then
-          echo "Generating manifests leaves tracked fiels in a modified state."
-          echo "Ensure to include updated manifests in this PR."
-          echo "This is usually done by running 'make manifests' and running 'git add ...' for the files that was modified by generating manifests."
-          git status -s
-          git diff
-          exit 1
-        fi
-    - shell: bash
-      run: |
-        make test
-      env:
-        HUMIO_E2E_LICENSE: ${{ secrets.HUMIO_E2E_LICENSE }}
-    - name: Publish Test Report
-      uses: mikepenz/action-junit-report@v2
-      if: always() # always run even if the previous step fails
-      with:
-        report_paths: '*-results-junit.xml'
-# Disable olm checks until we have a new bundle we want to validate against
-#  olm-checks:
-#    name: Run OLM Checks
-#    runs-on: ubuntu-latest
-#    steps:
-#    - uses: actions/checkout@v2
-#    - name: operator-sdk lint
-#      env:
-#        GO111MODULE: "on"
-#      uses: ./.github/action/operator-sdk
-#      with:
-#        args: operator-courier --verbose verify --ui_validate_io deploy/olm-catalog/humio-operator
+      - uses: actions/checkout@v2
+      - uses: actions/setup-go@v2
+        with:
+          go-version: "1.18.7"
+      - shell: bash
+        run: |
+          make manifests
+          if [[ -n $(git status -s) ]] ; then
+            echo "Generating manifests leaves tracked fiels in a modified state."
+            echo "Ensure to include updated manifests in this PR."
+            echo "This is usually done by running 'make manifests' and running 'git add ...' for the files that was modified by generating manifests."
+            git status -s
+            git diff
+            exit 1
+          fi
+      - shell: bash
+        run: |
+          make test
+        env:
+          HUMIO_E2E_LICENSE: ${{ secrets.HUMIO_E2E_LICENSE }}
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v2
+        if: always() # always run even if the previous step fails
+        with:
+          report_paths: "*-results-junit.xml"
+  # Disable olm checks until we have a new bundle we want to validate against
+  #  olm-checks:
+  #    name: Run OLM Checks
+  #    runs-on: ubuntu-latest
+  #    steps:
+  #    - uses: actions/checkout@v2
+  #    - name: operator-sdk lint
+  #      env:
+  #        GO111MODULE: "on"
+  #      uses: ./.github/action/operator-sdk
+  #      with:
+  #        args: operator-courier --verbose verify --ui_validate_io deploy/olm-catalog/humio-operator
   build:
     needs: checks
     name: Run Build
     runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      packages: write
     steps:
-    - uses: actions/checkout@v2
-    - uses: actions/setup-go@v2
-      with:
-        go-version: '1.18.7'
-    - name: operator image
-      run: make docker-build-operator IMG=humio/humio-operator:${{ github.sha }}
-    - name: helper image
-      run: make docker-build-helper IMG=humio/humio-operator-helper:${{ github.sha }}
-    - name: Set up Python
-      uses: actions/setup-python@v2
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install six
-    - name: CrowdStrike Container Image Scan Operator
-      uses: crowdstrike/container-image-scan-action@v0.7
-      with:
-        falcon_client_id: 1cd30708cb31442f85a6eec83279fe7b
-        container_repository: humio/humio-operator
-        container_tag: ${{ github.sha }}
-      env:
-        FALCON_CLIENT_SECRET: "${{ secrets.FALCON_CLIENT_SECRET }}"
-    - name: CrowdStrike Container Image Scan Operator Helper
-      uses: crowdstrike/container-image-scan-action@v0.7
-      with:
-        falcon_client_id: 1cd30708cb31442f85a6eec83279fe7b
-        container_repository: humio/humio-operator-helper
-        container_tag: ${{ github.sha }}
-      env:
-        FALCON_CLIENT_SECRET: "${{ secrets.FALCON_CLIENT_SECRET }}"
-    - name: Run Gosec Security Scanner
-      run: |
-        export PATH=$PATH:$(go env GOPATH)/bin
-        go get github.com/securego/gosec/cmd/gosec
-        go install github.com/securego/gosec/cmd/gosec
-        gosec ./...
-#    - name: Run Staticcheck
-#      uses: dominikh/staticcheck-action@v1.2.0
-#      with:
-#        version: "2022.1.3"
-#        install-go: false
+      - uses: actions/checkout@v2
+      - uses: actions/setup-go@v2
+        with:
+          go-version: "1.18.7"
+      - name: operator image
+        run: make docker-build-operator IMG=humio/humio-operator:${{ github.sha }}
+      - name: helper image
+        run: make docker-build-helper IMG=humio/humio-operator-helper:${{ github.sha }}
+      - name: Set up Python
+        uses: actions/setup-python@v2
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install six
+      - name: CrowdStrike Container Image Scan Operator
+        if: github.event.repository.fork == false
+        uses: crowdstrike/container-image-scan-action@v0.7
+        with:
+          falcon_client_id: 1cd30708cb31442f85a6eec83279fe7b
+          container_repository: humio/humio-operator
+          container_tag: ${{ github.sha }}
+        env:
+          FALCON_CLIENT_SECRET: "${{ secrets.FALCON_CLIENT_SECRET }}"
+      - name: CrowdStrike Container Image Scan Operator Helper
+        if: github.event.repository.fork == false
+        uses: crowdstrike/container-image-scan-action@v0.7
+        with:
+          falcon_client_id: 1cd30708cb31442f85a6eec83279fe7b
+          container_repository: humio/humio-operator-helper
+          container_tag: ${{ github.sha }}
+        env:
+          FALCON_CLIENT_SECRET: "${{ secrets.FALCON_CLIENT_SECRET }}"
+      - name: Run Gosec Security Scanner
+        run: |
+          export PATH=$PATH:$(go env GOPATH)/bin
+          go get github.com/securego/gosec/cmd/gosec
+          go install github.com/securego/gosec/cmd/gosec
+          gosec ./...
+
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@v2
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+      - name: push image
+        run: |
+          docker tag humio/humio-operator:${{ github.sha }} $IMG
+          docker rmi humio/humio-operator:${{ github.sha }}
+          make docker-push
+        env:
+          IMG: ghcr.io/${{ github.repository }}/humio-operator:${{ github.sha }}
+      - name: push image
+        run: |
+          docker tag humio/humio-operator-helper:${{ github.sha }} $IMG
+          docker rmi humio/humio-operator-helper:${{ github.sha }}
+          make docker-push
+        env:
+          IMG: ghcr.io/${{ github.repository }}/humio-operator-helper:${{ github.sha }}
